# Copyright (c) 2024 RIT Launch Initiative
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: cowsed
      url-base: git@github.com:cowsed

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import:
        name-allowlist:
          - cmsis
          - hal_st
          - hal_stm32
          - littlefs
          - loramac-node
          - hal_st
          - hal_espressif
          - lvgl
          - nanopb
          - mbedtls
          - fatfs
      clone-depth: 1

    - name: zephyr-meshtastic
      remote: cowsed
      revision: main

    - name: zephyr_pl_mpeg
      remote: cowsed
      revision: main
