# Copyright (c) 2024 RIT Launch Initiative
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: b5fdbc21bf7c86e6b11d67cf941b4efed36280fb # Day after 3.7 release for C++ net posix bugfix
      import:
        name-allowlist:
          - cmsis
          - hal_st
          - hal_stm32
          - littlefs
          - loramac-node
          - hal_st
      clone-depth: 1

