
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/aaron/.local/share/JetBrains/Toolbox/apps/clion-2/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "/home/aaron/Development/Launch/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/aaron/Development/Launch/zephyr/cmake/modules/zephyr_default.cmake:141 (include)"
      - "/home/aaron/Development/Launch/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/aaron/Development/Launch/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:125 (include_boilerplate)"
      - "/home/aaron/zephyrproject/zephyr/share/zephyr-package/cmake/zephyr_package_search.cmake:117 (include)"
      - "/home/aaron/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:152 (check_zephyr_package)"
      - "CMakeLists.txt:5 (find_package)"
    message: |
      The target system is: Generic - 3.7.99 - posix
      The host system is: Linux - 6.8.0-39-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/home/aaron/.local/share/JetBrains/Toolbox/apps/clion-2/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/home/aaron/.local/share/JetBrains/Toolbox/apps/clion-2/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/home/aaron/.local/share/JetBrains/Toolbox/apps/clion-2/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/aaron/Development/Launch/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/aaron/Development/Launch/zephyr/cmake/modules/zephyr_default.cmake:141 (include)"
      - "/home/aaron/Development/Launch/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/aaron/Development/Launch/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:125 (include_boilerplate)"
      - "/home/aaron/zephyrproject/zephyr/share/zephyr-package/cmake/zephyr_package_search.cmake:117 (include)"
      - "/home/aaron/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:152 (check_zephyr_package)"
      - "CMakeLists.txt:5 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/gcc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /home/aaron/Development/Launch/FSW/app/backplane/app_sensor_module/build-native-sim/CMakeFiles/3.29.6/CompilerIdC/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/home/aaron/.local/share/JetBrains/Toolbox/apps/clion-2/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/home/aaron/.local/share/JetBrains/Toolbox/apps/clion-2/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/home/aaron/.local/share/JetBrains/Toolbox/apps/clion-2/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "/home/aaron/Development/Launch/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "/home/aaron/Development/Launch/zephyr/cmake/modules/zephyr_default.cmake:141 (include)"
      - "/home/aaron/Development/Launch/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/aaron/Development/Launch/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:125 (include_boilerplate)"
      - "/home/aaron/zephyrproject/zephyr/share/zephyr-package/cmake/zephyr_package_search.cmake:117 (include)"
      - "/home/aaron/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:152 (check_zephyr_package)"
      - "CMakeLists.txt:5 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/g++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is GNU, found in:
        /home/aaron/Development/Launch/FSW/app/backplane/app_sensor_module/build-native-sim/CMakeFiles/3.29.6/CompilerIdCXX/a.out
      
  -
    kind: "message-v1"
    backtrace:
      - "/home/aaron/.local/share/JetBrains/Toolbox/apps/clion-2/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:1165 (message)"
      - "/home/aaron/.local/share/JetBrains/Toolbox/apps/clion-2/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/home/aaron/Development/Launch/zephyr/cmake/modules/kernel.cmake:134 (enable_language)"
      - "/home/aaron/Development/Launch/zephyr/cmake/modules/zephyr_default.cmake:141 (include)"
      - "/home/aaron/Development/Launch/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "/home/aaron/Development/Launch/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:125 (include_boilerplate)"
      - "/home/aaron/zephyrproject/zephyr/share/zephyr-package/cmake/zephyr_package_search.cmake:117 (include)"
      - "/home/aaron/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:152 (check_zephyr_package)"
      - "CMakeLists.txt:5 (find_package)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
      Copyright (C) 2023 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
...
