name: Build Native Sims

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "0 0 * * 1"
env:
  test_roots: |
    app/samples/openrocket_sensors
    app/samples/tenants_and_tasks

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    steps:

      - name: Install Native Sim Dependencies # native_sim goes for 32bit, not available by default
        run: sudo apt-get install -y gcc-multilib g++-multilib
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: FSW

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: python-${{ runner.os }}-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            python-${{ runner.os }}-
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Cache Zephyr dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/west
            ~/.cache/zephyr
          key: zephyr-${{ runner.os }}-${{ hashFiles('**/*.txt') }}
          restore-keys: |
            zephyr-${{ runner.os }}-


      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: FSW
          toolchains: arm-zephyr-eabi
          
      - name: Build firmware
        working-directory: FSW
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            EXTRA_TWISTER_FLAGS="--short-build-path -O/tmp/twister-out"
          fi
          west twister $(echo "${{ env.test_roots }}" | while IFS= read line; do if [[ $line = *[!\ ]* ]]; then echo -n " -T $line "; fi; done) -v --inline-logs --integration $EXTRA_TWISTER_FLAGS

